services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    user: root
    volumes:
      - ./users.json:/app/users.json
      - ./logs:/app/logs
      - ./templates:/app/templates
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Yekaterinburg
      - PYTHONUNBUFFERED=1
    env_file:
      - .env 